
name: Build Android APK

on:
  push:
    branches:
      - main # Or your default branch
    paths:
      - 'android/**' # Only run if files in android/ directory change
  pull_request:
    paths:
      - 'android/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Updated to v4

    - name: Set up JDK 17 # Updated to a more current JDK, but 11 is also fine if your project needs it
      uses: actions/setup-java@v4 # Updated to v4
      with:
        java-version: '17'
        distribution: 'temurin' 

    - name: Setup Gradle # Using official Gradle action for caching and setup
      uses: gradle/actions/setup-gradle@v3 # Updated to v3 of the composite action
      with:
        gradle-version: wrapper # Use the wrapper defined in the project

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew # Run from repo root

    - name: Build APK with Gradle
      run: ./gradlew assembleDebug
      working-directory: ./android # Execute ./gradlew from inside the android directory

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4 # Updated to v4
      with:
        name: app-debug.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
